### ISSUE TITLE
Aws\S3\Exception\S3Exception Error executing "ListObjects" 

### ISSUE THREAD

**Issue by GrytsenkoAndrey** [UniSharp/laravel-filemanager#1055]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Ubuntu 20.10
 * Laravel version : 8.26
 * Package version : 2.2
 * Steps to reproduce your issue :
 * Screenshots of browser console : 

I have next error sometimes

```
Aws\S3\Exception\S3Exception Error executing "ListObjects" 
AWS HTTP error: Server error: GET esulted in a 503 Slow Down response: <?xml version="1.0" encoding="UTF-8"?> <Error> <Code>SlowDown</Code> <Message>Reduce your request rate.</Message> </Erro (truncated...) SlowDown (server): Reduce your request rate. - <?xml version="1.0" encoding="UTF-8"?> <Error> <Code>SlowDown</Code> <Message>Reduce your request rate.</Message> </Error>
http://172.105.82.210:8100/laravel-filemanager/jsonitems?_=1615542952818&page=1&sort_type=alphabetic&type=image&working_dir=
Stack trace
Request
App
User
Context
Debug
Share 
Expand vendor frames
79
vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php
Aws\WrappedHttpHandler
:195
78
Aws\WrappedHttpHandler
:97

25 vendor frames…

1 unknown frame

50 vendor frames…
1
public/index.php
:52
Aws\WrappedHttpHandler::parseError
vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195
);

                $serviceError .= " {$parts['code']} ({$parts['type']}): "

                    . "{$parts['message']} - " . $err['response']->getBody();

            } catch (ParserException $e) {

                $parts = [];

                $serviceError .= ' Unable to parse error information from '

                    . "response - {$e->getMessage()}";

            }

 

            $parts['response'] = $err['response'];

        }

 

        $parts['exception'] = $err['exception'];

        $parts['request'] = $request;

        $parts['connection_error'] = !empty($err['connection_error']);

        $parts['transfer_stats'] = $stats;

 

        return new $this->exceptionClass(

            sprintf(

                'Error executing "%s" on "%s"; %s',

                $command->getName(),

                $request->getUri(),

                $serviceError

            ),

            $command,

            $parts,

            $err['exception']

        );

    }

}
#4 jsonitems?working_dir=&type=image&sort_type=alphabetic&page=1&_=1615542952818 (ajax) (11:56:03)
```

**Comment by GrytsenkoAndrey** [comment]
Yeah, and server is return 500 error,

I think it happens because of big quantity of objects (around 9 000 images in the bucket)

**Comment by kyranb** [comment]
Are you using S3 or Digital Ocean spaces by chance?

**Comment by GrytsenkoAndrey** [comment]
The problem is that bucket (space) has too many objects.
If you try to work with 100, 300 even 500 - no problems

**Comment by umeshgihub2020** [comment]
did anyone get any solution for this . 
I am trying to configure ckfinder with amazon s3 and getting the something like above mentioned error like this .

Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects" on "https://careerwill.s3.eu.amazonaws.com/?prefix=.ckfinder%2Fcache%2Fthumbs%2F.htaccess%2F&max-keys=1&encoding-type=url"; AWS HTTP error: cURL error 6: Could not resolve host: careerwill.s3.eu.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)' GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: careerwill.s3.eu.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\xampp\htdocs\ckeditor_4.10.0\ckfinder\core\connector\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:200 Stack trace: #0 D:\xampp\htdocs\ckeditor_4.10.0\ckfinder\core\connector\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\xampp\htdocs\ckeditor_4.10.0\ckfinder\core\connector\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFac in D:\xampp\htdocs\ckeditor_4.10.0\ckfinder\core\connector\php\vendor\aws\aws-sdk-php\src\WrappedHttpHandler.php on line 195


please tell me what I have missed
