### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by darko-vukadinovski** [UniSharp/laravel-filemanager#567]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system :
 * Laravel version :
 * Package version :
 * Steps to reproduce your issue :
 * Screenshots of browser console :

**Comment by darko-vukadinovski** [comment]
I have issue when I use the file manager on other domain.

I get this issue when I try to select picture from the file manager:

Uncaught DOMException: Blocked a frame with origin "http://127.0.0.1:8000" from accessing a cross-origin frame.
    at useTinymce4AndColorbox (http://127.0.0.1:8000/laravel-filemanager?field_name=mceu_44-inp&type=Images:600:12)
    at useFile (http://127.0.0.1:8000/laravel-filemanager?field_name=mceu_44-inp&type=Images:638:7)
    at HTMLDivElement.onclick (http://127.0.0.1:8000/laravel-filemanager?field_name=mceu_44-inp&type=Images:1:1)

**Comment by hmhofman** [comment]
@darko-vukadinovski Did you find a solution? 
I have the same problem. Can't figure out why. 
It used to work, be we haven't used the file manager for a while, so it is hard to find what changed that got it broken. 
Tried to turn off all security (even https) in nginx.conf, no luck. 
I found [this](https://www.tiny.cloud/docs-3x/howto/TinyMCE3x@How-to_load_TinyMCE_crossdomain/), but that is for TinyMCE3

I checked the domains and protocols with the developer tools, they all seem to come from the same domain. 
The iframe for TinyMCE does not have a document, so no origin? 
The iFrame for the laravel-filemanager loads from the same domain. 
Only the laravel-filemanager containes some js/css from cdn (cloudflare, bootstrapcdn)

And now I'm stuck...

**Comment by gwleuverink** [comment]
Hi @darko-vukadinovski, this most likely is not an issue with the file manager. If you use an API on a different domain you should add the appropriate CORS headers so your client can consume the remote API. Check out [barryvdh’s package](
https://github.com/barryvdh/laravel-cors)

**Comment by hmhofman** [comment]
@gwleuverink This did not work for me. 
As I see it, This is the hierarchy: 
```
- top Window -> Document (top)
|   |-> Textarea field (text)
|   |   |-> iFrame replaced (no origin, since the frame is filled from js). (text_ifr)
|   |-> Insert/edit image button (#mceu_??-button)
|
|-> Edit Dialog (.mce-floatpanel)
    |-> iFrame Laravel filemanager (lfm)
```
    
Seems like lfm needs to write to a field in the .mce-floatpanel (#mceu_123-inp) and then close. 
But that is not possible: 

Firefox: 
```
SecurityError: Permission denied to access property "document" on cross-origin object laravel-filemanager:600
	useTinymce4AndColorbox https://mysite.local/laravel-filemanager:600:5
	useFile https://mysite.local/laravel-filemanager:638:7
	<anoniem> https://mysite.local/laravel-filemanager:406:3
	dispatch jquery.js:4664:14
	add/r.handle jquery.js:4333:5
```
or (Chromium):
```
laravel-filemanager?field_name=mceu_59-inp&type=Images:600 Uncaught DOMException: Blocked a frame with origin "https://mysite.local" from accessing a cross-origin frame.
    at useTinymce4AndColorbox (https://mysite.local/laravel-filemanager?field_name=mceu_59-inp&type=Images:600:12)
    at useFile (https://mysite.local/laravel-filemanager?field_name=mceu_59-inp&type=Images:638:7)
    at HTMLDivElement.<anonymous> (https://mysite.local/laravel-filemanager?field_name=mceu_59-inp&type=Images:406:3)
    at HTMLDocument.dispatch (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js:3:8549)
    at HTMLDocument.r.handle (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js:3:5252)
```

Not sure what the source of the problem is. 
No browser Developer tools shows me  the frame name/id with corresponding domain/port/protocol. 
Not sure if the problem is with TinyMCE, LFM, or simply a browser update. 

Please point me in the right direction?

**Comment by gwleuverink** [comment]
Is the window with the filemanager you are opening on a different domain than where you are filling the input field on?

**Comment by hmhofman** [comment]
No. Everything should be on the same. 
References are relative. 
TinyMCE filebrowser Callback: 
```
file_browser_callback: function(fieldName, url, type, win) {
    var x = window.innerWidth ||
        document.documentElement.clientWidth ||
        document.getElementsByTagName('body')[0].clientWidth;
    var y = window.innerHeight ||
        document.documentElement.clientHeight ||
        document.getElementsByTagName('body')[0].clientHeight;

    var cmsURL = config.path_absolute + 'laravel-filemanager?field_name=' + fieldName;
    if (type == 'image') {
        cmsURL += '&type=Images';
    } else {
        cmsURL += '&type=Files';
    }

    tinyMCE.activeEditor.windowManager.open({
        file: cmsURL,
        title: 'Filemanager',
        width: x * 0.8,
        height: y * 0.8,
        resizable: 'yes',
        close_previous: 'no',
    });
},
```
on which the config.path_absolute is '/'.

**Comment by hmhofman** [comment]
Swapped LFM for [RFM](https://packagist.org/packages/cognitus/richfilemanager)
Same CORS Error. 
So this seems to be an error not/less with the FileManager. 
Remains: nginx (config?), Laravel, tinyMCE. 

Same error on both Production Server (Ubuntu 16.04 LTS) as Docker Development environment (nginx:alpine, phpdockerio/php7-fpm)

Simular error texts in Firefox 61 & Chromium 67
I would very much like to know where I made my mistake...

**Comment by hmhofman** [comment]
@gwleuverink Willem? 
Any Idea's?
Anybody else?

**Comment by gwleuverink** [comment]
Hey sorry for the late reply. I've been racking my brain about this but it is a really hard problem to debug. CORS errors have caused me my share of pain in the past. One thing I noticed, are you serving your development environment over https? I see https in your error output but not many people serve their dev domain over https so i'm wondering if that might be it. It's a long shot though

**Comment by hmhofman** [comment]
Yes. I set the dev to self-signed Https
Browsers keep bugging me about that every now and then, but I'm gives me the opportunity to debug protocol issues.

I tried changing to http also, same problem. It still could be a problem in nginx (settings), but it is not just Https.

Is there a browser that gives the right error on the right lines of code?
This problem does give me headaches.

**Comment by hmhofman** [comment]
Your opinion on work-arounds: 

**Loose the iframe**
Would it be possible to load the file manager inside a div instead of an iframe? 
That way, we don't have the CORS issue, right? 

**Load everything same-host**
PHP Scripts should already be on the same-host, so maybe the initiating code is from a CDN-served JS? Would it be an idea to load those through a (php) proxy of the same origin? 
That way everything should come from the same protocol, host, port. 
I know that would only account for the filemanager, not the client code (i.e. not TinyMCE, or initiating code)

**Comment by hmhofman** [comment]
Found it!
I set the document.domain flag elsewhere in code in order to communicate between cms and shop. 
It needs to be on your parent (top) window, on the iFrame AND on the file manager.

**Comment by dukinfotech** [comment]
> Found it!
> I set the document.domain flag elsewhere in code in order to communicate between cms and shop.
> It needs to be on your parent (top) window, on the iFrame AND on the file manager.

Can you show me what files i need document.domain? I have a same issue when using vuejs with laravel-filemanager. I'm using window.open instead of iframe. Thank you.

**Comment by jamal-alnaeb** [comment]
Good evening , i have same problem can any one share the solution for us please

**Comment by jamal-alnaeb** [comment]
Can you show me what files i need document.domain? I have a same issue when using vuejs with laravel-filemanager. I'm using window.open instead of iframe. Thank you.
