### ISSUE TITLE
Installation error on publish config: array_merge(): Argument #1 is not an array

### ISSUE THREAD

**Issue by carlotrimarchi** [UniSharp/laravel-filemanager#594]
* Operating system : macOS Sierra
 * Laravel version : Laravel Framework version 5.1.31 (LTS)
 * Package version : "~1.8"
 * Steps to reproduce your issue :
I'm trying to install the Unisharp Filemanager. I have been using the tsawler one, in combination with the CKeditor, till now, but since the project is abandoned I'm switching to this one.

I followed the installation instructions and when I try to run this command:
`php artisan vendor:publish --tag=lfm_config `
I get a list of errors:

```
[2018-05-10 10:14:04] local.ERROR: exception 'ErrorException' with message 'array_merge(): Argument #1 is not an array' in /Users/carlo/vagrant/projects/myproject/vendor/unisharp/laravel-filemanager/src/routes.php:6
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_merge(): ...', '/Users/carlo/va...', 6, Array)
#1 /Users/carlo/vagrant/projects/myproject/vendor/unisharp/laravel-filemanager/src/routes.php(6): array_merge(NULL, Array)
#2 /Users/carlo/vagrant/projects/myproject/vendor/unisharp/laravel-filemanager/src/LaravelFilemanagerServiceProvider.php(21): include('/Users/carlo/va...')
#3 [internal function]: Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider->boot()
#4 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#5 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#6 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider), 15)
#8 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#9 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /Users/carlo/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /Users/carlo/vagrant/projects/myproject/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}



  [ErrorException]
  array_merge(): Argument #1 is not an array
```
At this point, I can't run any `artisan` command. To go back to normal I have to manually delete the `vendor/unisharp` directory

**Comment by g0110280** [comment]
This is fixed in v2.0.0 alpha versions.
